name: Utc App ci/cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
      id-token: write
      contents: read
env:
  python_version: 3.11
  IMAGE_NAME: portfolio
  IMAGE_TAG: ${{ github.sha }}
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}
  ACCOUNT_ID: ${{secrets.ACCOUNT_ID}}
  ECR_REPO: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/jenkins-ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: ${{env.python_version}}

      - name: Install pytest
        run: pip install -r requirements.txt
      - name: unit test
        run: pytest test.py
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ------------------------
      # Build Docker Image
      # ------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ECR_REPO }}:${{env.IMAGE_TAG}} \
            .

      # ------------------------
      # Trivy Image Scan
      # ------------------------
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library

      # ------------------------
      # Tag & Push to ECR
      # ------------------------
      - name: Tag image
        run: |
          docker tag \
            ${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Push image to ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:${{ env.IMAGE_TAG }}
