name: Utc App ci/cd

on:
  push:
    branches: ["main"]

permissions:
  id-token: write  # ← Good, you have this!
  contents: read

env:
  IMAGE_NAME: jenkins-ci
  IMAGE_TAG: ${{ github.sha }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}  # ← ADD

      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: false
          vuln-type: os,library
     
      - name: Push to ECR
        run: |
          docker tag \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  
  ecs_deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}  # ← ADD
      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Render ecs task definition with new image
        id: taskdef
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-taskdef.json
          container-name: nginx
          image: /${{env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}
      
      - name: Deploy to ecs service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{steps.taskdef.outputs.task-definition}}
          cluster: nginx-fargate-cluster
          service: nginx-fargate-service
          wait-for-service-stability: true
      